export const levels = [
  {
    id: 1,
    name: 'Premiers Pas',
    description: 'Apprends les bases',
    target: 5,
    angle: 15,
    drift: 0,
    speedMult: 1,
    blockScale: 1,
    visibility: 1,
    reverse: false,
    doubleBlock: false,
    comboRequired: 0,
    perfectOnly: false,
    stars: { easy: 5, medium: 5, hard: 5 }
  },
  {
    id: 2,
    name: 'Vent Fort',
    description: 'Le bloc dérive pendant le drop',
    target: 8,
    angle: 30,
    drift: 0.003,
    speedMult: 1,
    blockScale: 1,
    visibility: 1,
    reverse: false,
    doubleBlock: false,
    comboRequired: 0,
    perfectOnly: false,
    stars: { easy: 8, medium: 8, hard: 8 }
  },
  {
    id: 3,
    name: 'Precision',
    description: 'Seuls les parfaits comptent',
    target: 5,
    angle: 30,
    drift: 0.001,
    speedMult: 1,
    blockScale: 1,
    visibility: 1,
    reverse: false,
    doubleBlock: false,
    comboRequired: 0,
    perfectOnly: true,
    stars: { easy: 5, medium: 5, hard: 5 }
  },
  {
    id: 4,
    name: 'Blocs Mini',
    description: 'Les blocs sont plus petits',
    target: 10,
    angle: 30,
    drift: 0.001,
    speedMult: 1,
    blockScale: 0.6,
    visibility: 1,
    reverse: false,
    doubleBlock: false,
    comboRequired: 0,
    perfectOnly: false,
    stars: { easy: 10, medium: 10, hard: 10 }
  },
  {
    id: 5,
    name: 'Chute Libre',
    description: 'Le bloc accélère très vite',
    target: 8,
    angle: 30,
    drift: 0.001,
    speedMult: 2,
    blockScale: 1,
    visibility: 1,
    reverse: false,
    doubleBlock: false,
    comboRequired: 0,
    perfectOnly: false,
    stars: { easy: 8, medium: 8, hard: 8 }
  },
  {
    id: 6,
    name: 'Combo Master',
    description: 'Atteins x5 de combo',
    target: 8,
    angle: 35,
    drift: 0.001,
    speedMult: 1,
    blockScale: 1,
    visibility: 1,
    reverse: false,
    doubleBlock: false,
    comboRequired: 5,
    perfectOnly: false,
    stars: { easy: 8, medium: 8, hard: 8 }
  },
  {
    id: 7,
    name: 'Nuit',
    description: 'Visibilité réduite',
    target: 8,
    angle: 40,
    drift: 0.002,
    speedMult: 1,
    blockScale: 1,
    visibility: 0.2,
    reverse: false,
    doubleBlock: false,
    comboRequired: 0,
    perfectOnly: false,
    stars: { easy: 8, medium: 8, hard: 8 }
  },
  {
    id: 8,
    name: 'Inversé',
    description: 'Le pendule s\'inverse à chaque bloc',
    target: 10,
    angle: 40,
    drift: 0.002,
    speedMult: 1,
    blockScale: 1,
    visibility: 1,
    reverse: true,
    doubleBlock: false,
    comboRequired: 0,
    perfectOnly: false,
    stars: { easy: 10, medium: 10, hard: 10 }
  },
  {
    id: 9,
    name: 'Double',
    description: '2 blocs swingent ensemble',
    target: 5,
    angle: 30,
    drift: 0.001,
    speedMult: 1,
    blockScale: 0.8,
    visibility: 1,
    reverse: false,
    doubleBlock: true,
    comboRequired: 0,
    perfectOnly: false,
    stars: { easy: 5, medium: 5, hard: 5 }
  },
  {
    id: 10,
    name: 'Boss',
    description: 'Mini + Nuit + Vent + Inversé',
    target: 8,
    angle: 50,
    drift: 0.003,
    speedMult: 1.5,
    blockScale: 0.6,
    visibility: 0.2,
    reverse: true,
    doubleBlock: false,
    comboRequired: 0,
    perfectOnly: false,
    stars: { easy: 8, medium: 8, hard: 8 }
  }
]
